package com.orion.proyectoorion.vivo

/**
 * Cadenas de UI para el modo Vivo en múltiples idiomas
 */
data class VivoStrings(
    val modeTitle: String,
    val modeDesc: String,
    val modeWarning: String,
    val statesDormant: String,
    val statesListening: String,
    val statesThinking: String,
    val statesSpeaking: String,
    val statesObserving: String,
    val tapToWake: String,
    val longPressToSleep: String,
    val requiresOpenAI: String,
    val permissionsNeeded: String,
    val connectionLost: String,
    val reconnecting: String,
    val audioIndicator: String,
    val visionIndicator: String,
    val connectionIndicator: String,
    val transcriptYou: String,
    val transcriptOrion: String,
    val experimentalBadge: String,
    val apiKeyRequired: String,
    val setupOpenAI: String,
    // Strings de pantalla
    val statusInitializing: String,
    val statusConnecting: String,
    val statusConnectingOpenAI: String,
    val statusReadyToListen: String,
    val statusConnected: String,
    val statusDisconnected: String,
    val tapButtonToSpeak: String,
    // Strings adicionales para VivoUI
    val statesReady: String,
    val microphoneNeeded: String,
    val invalidJsonFormat: String,
    val errorReadingFile: String,
    val cancel: String,
    val holdToStop: String,
    val memoryDataCount: String,  // "{name} · {count} datos"
    val modelRealtimeDesc: String,
    val modelRealtimeMiniDesc: String
)

val VIVO_ES = VivoStrings(
    modeTitle = "MODO VIVO",
    modeDesc = "Orion vive en tu teléfono. Ve, escucha y habla.",
    modeWarning = "⚡ Experimental · Requiere API OpenAI · Alto consumo de batería",
    statesDormant = "Dormido",
    statesListening = "Escuchando...",
    statesThinking = "Pensando...",
    statesSpeaking = "Hablando...",
    statesObserving = "Observando",
    tapToWake = "Toca para despertar",
    longPressToSleep = "Mantén presionado para dormir",
    requiresOpenAI = "Requiere API Key de OpenAI",
    permissionsNeeded = "Se necesitan permisos de micrófono y cámara",
    connectionLost = "Conexión perdida",
    reconnecting = "Reconectando...",
    audioIndicator = "Audio",
    visionIndicator = "Visión",
    connectionIndicator = "Conexión",
    transcriptYou = "Tú",
    transcriptOrion = "Orion",
    experimentalBadge = "EXPERIMENTAL",
    apiKeyRequired = "Necesitas configurar una API Key de OpenAI",
    setupOpenAI = "Configurar OpenAI",
    statusInitializing = "Iniciando...",
    statusConnecting = "Conectando...",
    statusConnectingOpenAI = "Conectando con OpenAI...",
    statusReadyToListen = "Listo para escuchar",
    statusConnected = "CONECTADO",
    statusDisconnected = "DESCONECTADO",
    tapButtonToSpeak = "Toca el botón para hablar",
    statesReady = "Listo",
    microphoneNeeded = "Se necesita micrófono",
    invalidJsonFormat = "Formato de JSON no válido",
    errorReadingFile = "Error leyendo archivo",
    cancel = "Cancelar",
    holdToStop = "Mantén para apagar",
    memoryDataCount = "datos",
    modelRealtimeDesc = "Máxima calidad · Mejor comprensión · Voz más natural",
    modelRealtimeMiniDesc = "Económico · Rápido · Ideal para uso diario"
)

val VIVO_EN = VivoStrings(
    modeTitle = "LIVE MODE",
    modeDesc = "Orion lives in your phone. Sees, hears and speaks.",
    modeWarning = "⚡ Experimental · Requires OpenAI API · High battery usage",
    statesDormant = "Dormant",
    statesListening = "Listening...",
    statesThinking = "Thinking...",
    statesSpeaking = "Speaking...",
    statesObserving = "Observing",
    tapToWake = "Tap to wake",
    longPressToSleep = "Long press to sleep",
    requiresOpenAI = "Requires OpenAI API Key",
    permissionsNeeded = "Microphone and camera permissions needed",
    connectionLost = "Connection lost",
    reconnecting = "Reconnecting...",
    audioIndicator = "Audio",
    visionIndicator = "Vision",
    connectionIndicator = "Connection",
    transcriptYou = "You",
    transcriptOrion = "Orion",
    experimentalBadge = "EXPERIMENTAL",
    apiKeyRequired = "You need to configure an OpenAI API Key",
    setupOpenAI = "Setup OpenAI",
    statusInitializing = "Initializing...",
    statusConnecting = "Connecting...",
    statusConnectingOpenAI = "Connecting to OpenAI...",
    statusReadyToListen = "Ready to listen",
    statusConnected = "CONNECTED",
    statusDisconnected = "DISCONNECTED",
    tapButtonToSpeak = "Tap button to speak",
    statesReady = "Ready",
    microphoneNeeded = "Microphone needed",
    invalidJsonFormat = "Invalid JSON format",
    errorReadingFile = "Error reading file",
    cancel = "Cancel",
    holdToStop = "Hold to stop",
    memoryDataCount = "facts",
    modelRealtimeDesc = "Maximum quality · Better understanding · More natural voice",
    modelRealtimeMiniDesc = "Affordable · Fast · Ideal for daily use"
)

val VIVO_CN = VivoStrings(
    modeTitle = "活体模式",
    modeDesc = "Orion生活在你的手机里。看、听、说。",
    modeWarning = "⚡ 实验性 · 需要OpenAI API · 高电池消耗",
    statesDormant = "休眠",
    statesListening = "聆听中...",
    statesThinking = "思考中...",
    statesSpeaking = "说话中...",
    statesObserving = "观察中",
    tapToWake = "点击唤醒",
    longPressToSleep = "长按休眠",
    requiresOpenAI = "需要OpenAI API密钥",
    permissionsNeeded = "需要麦克风和相机权限",
    connectionLost = "连接丢失",
    reconnecting = "重新连接中...",
    audioIndicator = "音频",
    visionIndicator = "视觉",
    connectionIndicator = "连接",
    transcriptYou = "你",
    transcriptOrion = "Orion",
    experimentalBadge = "实验性",
    apiKeyRequired = "您需要配置OpenAI API密钥",
    setupOpenAI = "配置OpenAI",
    statusInitializing = "初始化中...",
    statusConnecting = "连接中...",
    statusConnectingOpenAI = "正在连接OpenAI...",
    statusReadyToListen = "准备聆听",
    statusConnected = "已连接",
    statusDisconnected = "未连接",
    tapButtonToSpeak = "点击按钮说话",
    statesReady = "准备就绪",
    microphoneNeeded = "需要麦克风权限",
    invalidJsonFormat = "JSON格式无效",
    errorReadingFile = "读取文件错误",
    cancel = "取消",
    holdToStop = "长按停止",
    memoryDataCount = "条数据",
    modelRealtimeDesc = "最高质量 · 更好理解 · 更自然的声音",
    modelRealtimeMiniDesc = "经济实惠 · 快速 · 日常使用理想"
)

val VIVO_FR = VivoStrings(
    modeTitle = "MODE VIVANT",
    modeDesc = "Orion vit dans votre téléphone. Voit, écoute et parle.",
    modeWarning = "⚡ Expérimental · Nécessite API OpenAI · Haute consommation",
    statesDormant = "Endormi",
    statesListening = "Écoute...",
    statesThinking = "Réflexion...",
    statesSpeaking = "Parle...",
    statesObserving = "Observe",
    tapToWake = "Touchez pour réveiller",
    longPressToSleep = "Appui long pour dormir",
    requiresOpenAI = "Nécessite une clé API OpenAI",
    permissionsNeeded = "Permissions micro et caméra nécessaires",
    connectionLost = "Connexion perdue",
    reconnecting = "Reconnexion...",
    audioIndicator = "Audio",
    visionIndicator = "Vision",
    connectionIndicator = "Connexion",
    transcriptYou = "Vous",
    transcriptOrion = "Orion",
    experimentalBadge = "EXPÉRIMENTAL",
    apiKeyRequired = "Vous devez configurer une clé API OpenAI",
    setupOpenAI = "Configurer OpenAI",
    statusInitializing = "Initialisation...",
    statusConnecting = "Connexion...",
    statusConnectingOpenAI = "Connexion à OpenAI...",
    statusReadyToListen = "Prêt à écouter",
    statusConnected = "CONNECTÉ",
    statusDisconnected = "DÉCONNECTÉ",
    tapButtonToSpeak = "Appuyez pour parler",
    statesReady = "Prêt",
    microphoneNeeded = "Microphone nécessaire",
    invalidJsonFormat = "Format JSON invalide",
    errorReadingFile = "Erreur de lecture du fichier",
    cancel = "Annuler",
    holdToStop = "Maintenez pour arrêter",
    memoryDataCount = "données",
    modelRealtimeDesc = "Qualité maximale · Meilleure compréhension · Voix plus naturelle",
    modelRealtimeMiniDesc = "Économique · Rapide · Idéal pour usage quotidien"
)

val VIVO_RU = VivoStrings(
    modeTitle = "ЖИВОЙ РЕЖИМ",
    modeDesc = "Orion живёт в вашем телефоне. Видит, слышит и говорит.",
    modeWarning = "⚡ Экспериментально · Требуется API OpenAI · Высокий расход батареи",
    statesDormant = "Спящий",
    statesListening = "Слушает...",
    statesThinking = "Думает...",
    statesSpeaking = "Говорит...",
    statesObserving = "Наблюдает",
    tapToWake = "Нажмите для пробуждения",
    longPressToSleep = "Удерживайте для сна",
    requiresOpenAI = "Требуется API ключ OpenAI",
    permissionsNeeded = "Нужны разрешения микрофона и камеры",
    connectionLost = "Соединение потеряно",
    reconnecting = "Переподключение...",
    audioIndicator = "Аудио",
    visionIndicator = "Видение",
    connectionIndicator = "Связь",
    transcriptYou = "Вы",
    transcriptOrion = "Орион",
    experimentalBadge = "ЭКСПЕРИМЕНТ",
    apiKeyRequired = "Вам нужно настроить API ключ OpenAI",
    setupOpenAI = "Настроить OpenAI",
    statusInitializing = "Инициализация...",
    statusConnecting = "Подключение...",
    statusConnectingOpenAI = "Подключение к OpenAI...",
    statusReadyToListen = "Готов слушать",
    statusConnected = "ПОДКЛЮЧЕНО",
    statusDisconnected = "ОТКЛЮЧЕНО",
    tapButtonToSpeak = "Нажмите кнопку для разговора",
    statesReady = "Готов",
    microphoneNeeded = "Нужен микрофон",
    invalidJsonFormat = "Неверный формат JSON",
    errorReadingFile = "Ошибка чтения файла",
    cancel = "Отмена",
    holdToStop = "Удерживайте для остановки",
    memoryDataCount = "данных",
    modelRealtimeDesc = "Максимальное качество · Лучшее понимание · Более естественный голос",
    modelRealtimeMiniDesc = "Экономичный · Быстрый · Идеален для ежедневного использования"
)

val VIVO_PT = VivoStrings(
    modeTitle = "MODO VIVO",
    modeDesc = "Orion vive no seu telefone. Vê, ouve e fala.",
    modeWarning = "⚡ Experimental · Requer API OpenAI · Alto consumo de bateria",
    statesDormant = "Dormindo",
    statesListening = "Ouvindo...",
    statesThinking = "Pensando...",
    statesSpeaking = "Falando...",
    statesObserving = "Observando",
    tapToWake = "Toque para acordar",
    longPressToSleep = "Pressione para dormir",
    requiresOpenAI = "Requer API Key do OpenAI",
    permissionsNeeded = "Permissões de microfone e câmera necessárias",
    connectionLost = "Conexão perdida",
    reconnecting = "Reconectando...",
    audioIndicator = "Áudio",
    visionIndicator = "Visão",
    connectionIndicator = "Conexão",
    transcriptYou = "Você",
    transcriptOrion = "Orion",
    experimentalBadge = "EXPERIMENTAL",
    apiKeyRequired = "Você precisa configurar uma API Key do OpenAI",
    setupOpenAI = "Configurar OpenAI",
    statusInitializing = "Iniciando...",
    statusConnecting = "Conectando...",
    statusConnectingOpenAI = "Conectando ao OpenAI...",
    statusReadyToListen = "Pronto para ouvir",
    statusConnected = "CONECTADO",
    statusDisconnected = "DESCONECTADO",
    tapButtonToSpeak = "Toque no botão para falar",
    statesReady = "Pronto",
    microphoneNeeded = "Microfone necessário",
    invalidJsonFormat = "Formato JSON inválido",
    errorReadingFile = "Erro ao ler arquivo",
    cancel = "Cancelar",
    holdToStop = "Segure para parar",
    memoryDataCount = "dados",
    modelRealtimeDesc = "Qualidade máxima · Melhor compreensão · Voz mais natural",
    modelRealtimeMiniDesc = "Econômico · Rápido · Ideal para uso diário"
)

fun getVivoStrings(langCode: String): VivoStrings = when(langCode) {
    "ES" -> VIVO_ES
    "EN" -> VIVO_EN
    "CN" -> VIVO_CN
    "FR" -> VIVO_FR
    "RU" -> VIVO_RU
    "PT" -> VIVO_PT
    else -> VIVO_EN
}